version: '3'

services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: myapp
        restart: unless-stopped
        environment:
            APP_ENV: dev
            APP_SECRET: mysecret
            DATABASE_URL: mysql://root:password@db/mydb
        volumes:
            - .:/var/www/html
        networks:
            - mynetwork
        command: php-fpm

volumes:
    db_data:

networks:
    mynetwork:
